Repository openSUSE/pytest-xmlcomp, pull requests merged in 2018-06, with the labels that each got.

#43 Improve README.rst
  README.rst
Labels: doc :books:, enhancement :ice_cream:

#48 Prepare "real" documentation
  .bumpversion.cfg
  docs/conf.py
  docs/index.rst
  docs/modules.rst
  docs/pytest.inv
  docs/pytest_xmlcomp.rst
  docs/requirements.pip
  pytest_xmlcomp/__init__.py
  pytest_xmlcomp/hooks.py
  pytest_xmlcomp/plugin.py
Labels: doc :books:

#46 Add namespace support
  pytest_xmlcomp/plugin.py
  tests/conftest.py
  tests/data/bad/article-002.json
  tests/data/bad/article-002.xml
  tests/data/bad_namesp/article006.json
  tests/data/bad_namesp/article006.xml
  tests/data/good/article-001.json
  tests/data/good_namesp/article-005.json
  tests/data/good_namesp/article-005.xml
  tests/data/json_syn_error/article-004.json
  tests/data/json_syn_error_nsp/article-007.json
  tests/data/json_syn_error_nsp/article-007.xml
  tests/data/xml_syn_error/article-003.json
  tests/data/xml_syn_error/article-003.xml
  tests/test_xmlcomp.py
Labels: enhancement :ice_cream:
